php_site_supported_versions:
  - "7.4"
  - "8.0"
  - "8.1"
  - "8.2"
  - "8.3"
  - "8.4"
  - "8.5"

php_site_packages:
  - "php{{ site.php_version }}"
  - "php{{ site.php_version }}-fpm"
  - "php{{ site.php_version }}-cli"
  - "php{{ site.php_version }}-mysql"
  - "php{{ site.php_version }}-xml"
  - "php{{ site.php_version }}-curl"
  - "php{{ site.php_version }}-mbstring"
  - "php{{ site.php_version }}-zip"
